# Generated by Django 2.2.13 on 2020-06-11 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="hsgfhadgfa",
            field=models.ManyToManyField(
                blank=True,
                related_name="customtext_hsgfhadgfa",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="jhgdfjhgsafa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_jhgdfjhgsafa",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="jhgdskghaef",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_jhgdskghaef",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="jhgjhgsghfhfg",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_jhgjhgsghfhfg",
                to="home.HomePage",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="nshgdfjagsfa",
            field=models.ManyToManyField(
                blank=True, related_name="customtext_nshgdfjagsfa", to="home.CustomText"
            ),
        ),
    ]
