# Generated by Django 2.2.13 on 2020-06-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200611_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hsgfhadgfa',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgdfjhgsafa',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgdskghaef',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjhgsghfhfg',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='nshgdfjagsfa',
        ),
    ]
